services:
  - type: web
    name: student-grievance-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PORT
        value: 5000